services:
  postgres:
    image: postgres:16
    container_name: repairshop-db
    environment:
      POSTGRES_USER: repairshop
      POSTGRES_PASSWORD: repairshop
      POSTGRES_DB: repairshop
    ports:
      - "5432:5432"
    volumes:
      - repairshop-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U repairshop"]
      interval: 5s
      timeout: 3s
      retries: 5
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    environment:
      MP_MAX_MESSAGES: 500
    ports:
      - "1025:1025" # Porta SMTP
      - "8025:8025" # Porta Interface Web (Dashboard)
  app:
    build: .
    container_name: repairshop-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/repairshop
      SPRING_DATASOURCE_USERNAME: repairshop
      SPRING_DATASOURCE_PASSWORD: repairshop
      SPRING_MAIL_HOST: mailpit
      SPRING_MAIL_PORT: 1025
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  repairshop-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
