# A chave que você acabou de criar no Passo 1
sonar.projectKey=repairshop-local

# Aponta para o seu Docker local (ajuste a porta se necessário)
sonar.host.url=http://localhost:9000

# O SonarQube Community NÃO usa a propriedade sonar.organization, então apague essa linha!

# O caminho do JaCoCo continua idêntico
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml