apiVersion: v1
kind: Secret
metadata:
  name: repairshop-db-credentials
  namespace: repairshop
  labels:
    app: repairshop
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: repairshop
  SPRING_DATASOURCE_PASSWORD: repairshop
  POSTGRES_USER: repairshop
  POSTGRES_PASSWORD: repairshop
  POSTGRES_DB: repairshop
