apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: repairshop-hpa
  namespace: repairshop
  labels:
    app: repairshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: repairshop-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 20
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 20
    scaleDown:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
