apiVersion: v1
kind: Secret
metadata:
  name: repairshop-db-credentials
  namespace: repairshop
  labels:
    app: repairshop
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: DB_USERNAME
  SPRING_DATASOURCE_PASSWORD: DB_PASSWORD
  POSTGRES_USER: DB_USERNAME
  POSTGRES_PASSWORD: DB_PASSWORD
