apiVersion: v1
kind: Service
metadata:
  name: repairshop-service
  namespace: repairshop
  labels:
    app: repairshop
spec:
  selector:
    app: repairshop
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer
