apiVersion: v1
kind: Service
metadata:
  name: repairshop-service
  namespace: repairshop
  labels:
    app: repairshop
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: repairshop
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer

