apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Recursos base do projeto
  - ../deployment.yaml
  - ../service.yaml
  - ../configmap.yaml
  - ../hpa.yaml
  - ../mailhog-deployment.yaml
  - ../mailhog-service.yaml
  # Segredo com credenciais genéricas
  - ./secret-aws.yaml

# Substituição automática da imagem de produção pela imagem do ECR
# O usuário deve trocar <SUA_CONTA_AWS> pelo ID real de sua conta AWS
images:
  - name: ECR_REGISTRY/repairshop
    newName: <SUA_CONTA_AWS>.dkr.ecr.us-east-1.amazonaws.com/repairshop
    newTag: latest
