apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Recursos base do projeto
  - ../deployment.yaml
  - ../service.yaml
  - ../configmap.yaml
  - ../hpa.yaml
  - ../mailpit-deployment.yaml
  - ../mailpit-service.yaml
  - ../secret.yaml

# Substituição automática da imagem de produção pela imagem do ECR
images:
  - name: ECR_REGISTRY/repairshop
    newName: <SUA_CONTA_AWS>.dkr.ecr.us-east-1.amazonaws.com/repairshop
    newTag: latest
