apiVersion: v1
kind: ConfigMap
metadata:
  name: repairshop-config
  namespace: repairshop
  labels:
    app: repairshop
    env: prd
data:
  SPRING_APPLICATION_NAME: repairshop
  SPRING_PROFILES_ACTIVE: prd
  SPRING_MAIL_HOST: smtp.aws.internal
  SPRING_MAIL_PORT: "587"
  SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/repairshop
  LOGGING_LEVEL_COM_CAO_REPAIRSHOP: INFO
