apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: repairshop

resources:
  - otel-collector.yaml
  - prometheus.yaml
  - jaeger.yaml
  - loki.yaml

configMapGenerator:
  - name: otel-collector-config
    files:
      - configs/otel-collector-config.yaml
  - name: prometheus-config
    files:
      - configs/prometheus.yml
  - name: loki-config
    files:
      - configs/loki.yml
